apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-monitor-metrics-config
  namespace: argocd
spec:
  project: platform
  source:
    path: platform/monitoring/config
    repoURL: https://github.com/tukue/azure-platform-gitops.git
    targetRevision: main
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
