apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository-config.yaml
  - project.yaml
  - platform.yaml
  - applications.yaml
replacements:
  - source:
      kind: ConfigMap
      name: gitops-repository
      fieldPath: data.repoURL
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.repoURL
      - select:
          kind: AppProject
        fieldPaths:
          - spec.sourceRepos.0
