apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-key-vault-reader
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: REPLACE_WITH_TERRAFORM_EXTERNAL_SECRETS_CLIENT_ID
    azure.workload.identity/tenant-id: REPLACE_WITH_TERRAFORM_TENANT_ID
