apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: REPLACE_WITH_TERRAFORM_KEY_VAULT_URI
      tenantId: REPLACE_WITH_TERRAFORM_TENANT_ID
      serviceAccountRef:
        name: azure-key-vault-reader
        namespace: external-secrets
