output "resource_group_name" { value = azurerm_resource_group.this.name }
output "aks_name" { value = module.aks.name }
output "aks_fqdn" { value = module.aks.fqdn }
output "acr_name" { value = module.acr.name }
output "acr_login_server" { value = module.acr.login_server }
output "aks_oidc_issuer_url" { value = module.aks.oidc_issuer_url }
output "aks_kubelet_identity_object_id" { value = module.aks.kubelet_identity_object_id }
output "log_analytics_workspace_id" { value = module.observability.log_analytics_workspace_id }
output "log_analytics_workspace_name" { value = module.observability.log_analytics_workspace_name }
output "azure_monitor_workspace_id" { value = module.observability.monitor_workspace_id }
output "azure_managed_grafana_endpoint" { value = module.observability.grafana_endpoint }
output "azure_monitor_private_link_scope_id" { value = var.observability_private_link_enabled ? module.monitor_private_link[0].id : null }
output "key_vault_name" { value = module.key_vault.name }
output "key_vault_uri" { value = module.key_vault.vault_uri }
output "external_secrets_client_id" { value = module.key_vault.external_secrets_client_id }
output "tenant_id" { value = data.azurerm_client_config.current.tenant_id }
output "cmk_key_vault_name" { value = var.cmk_enabled ? module.cmk[0].key_vault_name : null }
output "aks_disk_encryption_set_id" { value = var.cmk_enabled ? module.cmk[0].disk_encryption_set_id : null }
output "managed_hsm_uri" { value = var.managed_hsm_enabled ? module.managed_hsm[0].hsm_uri : null }
