resource "azurerm_user_assigned_identity" "backup" {
  name                = "id-${var.name}-backup"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

resource "azapi_resource" "this" {
  type      = "Microsoft.HardwareSecurityModules/cloudHsmClusters@2025-03-31"
  name      = var.name
  parent_id = var.resource_group_id
  location  = var.location
  tags      = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.backup.id]
  }

  body = {
    properties = {
      autoGeneratedDomainNameLabelScope = "SubscriptionReuse"
      publicNetworkAccess               = "Disabled"
    }
    sku = {
      capacity = var.sku_capacity
      family   = "B"
      name     = "Standard_B1"
    }
  }
}

resource "azurerm_private_dns_zone" "this" {
  name                = "privatelink.cloudhsm.azure.net"
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "this" {
  name                  = "pdnslink-${var.name}"
  resource_group_name   = var.resource_group_name
  private_dns_zone_name = azurerm_private_dns_zone.this.name
  virtual_network_id    = var.virtual_network_id
  registration_enabled  = false
  tags                  = var.tags
}

resource "azurerm_private_endpoint" "this" {
  name                = "pep-${var.name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.private_endpoint_subnet_id
  tags                = var.tags

  private_service_connection {
    name                           = "psc-${var.name}"
    private_connection_resource_id = azapi_resource.this.id
    subresource_names              = ["cloudhsmclusters"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [azurerm_private_dns_zone.this.id]
  }
}
