apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-api-runtime
  namespace: "demo"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault
  target:
    name: demo-api-runtime
    creationPolicy: Owner
  data:
    - secretKey: runtime-token
      remoteRef:
        key: "demo-api-runtime-token"
