apiVersion: v1
kind: Namespace
metadata:
  name: "demo"
  labels:
    app.kubernetes.io/managed-by: "platform-golden-path"
    platform.example.com/owner: "platform-team"
    platform.example.com/environment: "dev"
    platform.example.com/cost-center: "platform-team"
    pod-security.kubernetes.io/enforce: "restricted"
