apiVersion: v1
kind: ServiceAccount
metadata:
  name: "demo-api"
  namespace: "demo"
  labels:
    app.kubernetes.io/name: "demo-api"
    app.kubernetes.io/managed-by: "platform-golden-path"
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_TERRAFORM_CRYPTO_DEMO_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_TERRAFORM_TENANT_ID"
automountServiceAccountToken: false
