apiVersion: v1
kind: ServiceAccount
metadata:
  name: crypto-demo-api
  namespace: demo
  annotations:
    azure.workload.identity/client-id: REPLACE_WITH_TERRAFORM_CRYPTO_DEMO_CLIENT_ID
    azure.workload.identity/tenant-id: REPLACE_WITH_TERRAFORM_TENANT_ID
